Results Page, Landing Page, Static CSS
anandimous/DAM pull request #60
Opened 2018-10-17 14:30 UTC by lawzeem

Added results page to display items name and description from inventory model.
Added a landing page with a button that redirects to results page.
Added the CSS files to the static folder so they can be used anywhere.

2018-10-17 15:05 UTC, StephenOrJames requested changes
Please remove the `.idea` directory (and perhaps add it to `.gitignore`).

2018-10-17 15:05 UTC, StephenOrJames commented on dam/index/templates/index/index.html
> +    <title>DAM</title>
The `title` should be in the `head` of the page, not the `body`.

2018-10-17 15:05 UTC, StephenOrJames commented on dam/settings.py
> +# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
Could you please remove this line if it isn't being used?

2018-10-17 15:05 UTC, StephenOrJames commented on dam/settings.py
> +STATIC_DIRS = 'static'
Since `STATIC_DIRS` isn't a Django setting and isn't being reused, could you specify the value directly in `STATICFILES_DIRS`?

Also, Django's recommendation is to use full paths ([see docs](https://docs.djangoproject.com/en/2.1/ref/settings/#staticfiles-dirs)), so I'd suggest doing something like `os.path.join(BASE_DIR, 'static')` (`BASE_DIR` is already an absolute path). in `STATICFILES_DIRS`.

2018-10-17 15:05 UTC, StephenOrJames commented on dam/settings.py
> +        'DIRS': [
You shouldn't need to change this: `APP_DIRS` is `True`, so Django should automatically check those directories (provided that the relevant apps are installed).

2018-10-17 15:05 UTC, StephenOrJames commented on dam/settings.py
> +    'dam.results',
Please maintain the ordering so that it's easier to find things.

2018-10-17 15:05 UTC, StephenOrJames commented on dam/results/views.py
> +from django.shortcuts import render
In my mind, this belongs in the `inventory` app (rather than its own app). Thoughts on moving this there instead?

2018-10-17 19:35 UTC, lawzeem commented on dam/index/templates/index/index.html
> +    <title>DAM</title>
Since I am extending base.html, the body is what gets changed. Having the Title in the body allows me to change it in each template.

2018-10-17 19:43 UTC, lawzeem commented on dam/settings.py
> +        'DIRS': [
If I don't have the individual directories, the I get an error of TemplateDoesNotExist

2018-10-17 23:10 UTC, lawzeem commented on dam/settings.py
> +    'dam.results',
Done

2018-10-19 21:57 UTC, StephenOrJames commented
Superseded by smaller tasks/PRs.

2018-10-19 21:57 UTC, closed without merging